### ISSUE TITLE
Peer Review Gabriele Iurlaro

### ISSUE THREAD

**Issue by gabbiurlaro** [lorenzobellino/Computational-Intelligence-2022#1]
### General Comments

I really appreciate your readme file, it's very clear. Also, your heuristic is very good, and in many case converges to the global optimum(5, 10, 20).

I also agree wiht you to find a trade-off between exact solution and computation complexity.

### Code suggestion

- I didin't understand well your code, some comments can help.
- Why you used a prioritized set? And why you inserted it into a priority queue? Didn't was enough to put into the priority queue?

**Comment by lorenzobellino** [comment]
Thank's for the suggestion! 
I updated my code to remove the usage of ```PrioritizedSet``` instead opting to use a tuple representing ```(priority,list)```.
I also tried to add some comment to my code in order to make it more readble.
I will close this Issue but if you have more suggestion feel free to open a new one.
