### ISSUE TITLE
Review by Angelica

### ISSUE THREAD

**Issue by angelicaferlin** [lorenzobellino/Computational-Intelligence-2022#2]
## General impression
I think you have done a good job of finding a solution with the tradeoffs you presented in the readme. Your readme is highly appreciated, and I like that it is thoroughly written. 

## Small suggestion

- Some parts of your code could become easier to understand by dividing it into smaller steps with good variable names. For example, I would suggest dividing the line presented below into sublines for a better understaning, perhaps declaring "int(100*len(element)/N" as a varible. 
```
 options.put(PrioritizedSet(int(100*len(element)/N),element))
```

- Good use of docstrings and I think it the code could be more easily understandable with some more comments in your search-function. 

- Good idea to implement the weight as percentage of new coverage in each set.

**Comment by lorenzobellino** [comment]
Thank's for the suggestion and appreciation! 
I tried to add some comment to my code in order to make it more understandable.
I will close this Issue but if you have more suggestion feel free to open a new one.
